export interface Country {
  name: string;
  code: string;
  dialCode: string;
}

export const COUNTRIES: Country[] = [
  { name: "Nigeria", code: "NG", dialCode: "+234" },
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Ghana", code: "GH", dialCode: "+233" },
  { name: "South Africa", code: "ZA", dialCode: "+27" },
  { name: "Kenya", code: "KE", dialCode: "+254" },
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "Germany", code: "DE", dialCode: "+49" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "Brazil", code: "BR", dialCode: "+55" },
  { name: "Australia", code: "AU", dialCode: "+61" },
  { name: "Japan", code: "JP", dialCode: "+81" },
  { name: "China", code: "CN", dialCode: "+86" },
  { name: "Egypt", code: "EG", dialCode: "+20" },
  { name: "Tanzania", code: "TZ", dialCode: "+255" },
  { name: "Uganda", code: "UG", dialCode: "+256" },
  { name: "Cameroon", code: "CM", dialCode: "+237" },
  { name: "Netherlands", code: "NL", dialCode: "+31" },
  { name: "Switzerland", code: "CH", dialCode: "+41" },
  { name: "Singapore", code: "SG", dialCode: "+65" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
  { name: "Turkey", code: "TR", dialCode: "+90" },
  { name: "Mexico", code: "MX", dialCode: "+52" },
  { name: "Argentina", code: "AR", dialCode: "+54" },
  { name: "Colombia", code: "CO", dialCode: "+57" },
  { name: "Spain", code: "ES", dialCode: "+34" },
  { name: "Italy", code: "IT", dialCode: "+39" },
  { name: "Portugal", code: "PT", dialCode: "+351" },
  { name: "Poland", code: "PL", dialCode: "+48" },
  { name: "Indonesia", code: "ID", dialCode: "+62" },
  { name: "Philippines", code: "PH", dialCode: "+63" },
  { name: "Thailand", code: "TH", dialCode: "+66" },
  { name: "Vietnam", code: "VN", dialCode: "+84" },
  { name: "Malaysia", code: "MY", dialCode: "+60" },
  { name: "South Korea", code: "KR", dialCode: "+82" },
  { name: "Pakistan", code: "PK", dialCode: "+92" },
  { name: "Bangladesh", code: "BD", dialCode: "+880" },
  { name: "Russia", code: "RU", dialCode: "+7" },
  { name: "Ukraine", code: "UA", dialCode: "+380" },
];
